package dao;

import entity.CloudUser;
import entity.CloudUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    long countByExample(CloudUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int deleteByExample(CloudUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int insert(CloudUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int insertSelective(CloudUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    List<CloudUser> selectByExample(CloudUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    CloudUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") CloudUser record, @Param("example") CloudUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int updateByExample(@Param("record") CloudUser record, @Param("example") CloudUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int updateByPrimaryKeySelective(CloudUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_user
     *
     * @mbg.generated Fri Jan 19 18:21:40 CST 2018
     */
    int updateByPrimaryKey(CloudUser record);
}