#datasource
spring.datasource:
      url: jdbc:mysql://localhost:3306/sunrise?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      druid.initial-size: 1
      druid.max-active: 20
      druid.min-idle: 1


#jwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml


logging.level.org.springframework.security: debug








