package entity;

import java.util.Date;

public class CloudUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.account
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.password
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.name
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.college_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Long college_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.profession_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Long profession_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.class_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Long class_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.mail
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.mobile_phone
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String mobile_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.create_date
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.update_date
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.job_number
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String job_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.job_title
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String job_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.student_number
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Integer student_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.role_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private Long role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_user.salt
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.id
     *
     * @return the value of cloud_user.id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.id
     *
     * @param id the value for cloud_user.id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.account
     *
     * @return the value of cloud_user.account
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.account
     *
     * @param account the value for cloud_user.account
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.password
     *
     * @return the value of cloud_user.password
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.password
     *
     * @param password the value for cloud_user.password
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.name
     *
     * @return the value of cloud_user.name
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.name
     *
     * @param name the value for cloud_user.name
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.college_id
     *
     * @return the value of cloud_user.college_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Long getCollege_id() {
        return college_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.college_id
     *
     * @param college_id the value for cloud_user.college_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setCollege_id(Long college_id) {
        this.college_id = college_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.profession_id
     *
     * @return the value of cloud_user.profession_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Long getProfession_id() {
        return profession_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.profession_id
     *
     * @param profession_id the value for cloud_user.profession_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setProfession_id(Long profession_id) {
        this.profession_id = profession_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.class_id
     *
     * @return the value of cloud_user.class_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.class_id
     *
     * @param class_id the value for cloud_user.class_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.mail
     *
     * @return the value of cloud_user.mail
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.mail
     *
     * @param mail the value for cloud_user.mail
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.mobile_phone
     *
     * @return the value of cloud_user.mobile_phone
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getMobile_phone() {
        return mobile_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.mobile_phone
     *
     * @param mobile_phone the value for cloud_user.mobile_phone
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setMobile_phone(String mobile_phone) {
        this.mobile_phone = mobile_phone == null ? null : mobile_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.create_date
     *
     * @return the value of cloud_user.create_date
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.create_date
     *
     * @param create_date the value for cloud_user.create_date
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.update_date
     *
     * @return the value of cloud_user.update_date
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.update_date
     *
     * @param update_date the value for cloud_user.update_date
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.job_number
     *
     * @return the value of cloud_user.job_number
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getJob_number() {
        return job_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.job_number
     *
     * @param job_number the value for cloud_user.job_number
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setJob_number(String job_number) {
        this.job_number = job_number == null ? null : job_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.job_title
     *
     * @return the value of cloud_user.job_title
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getJob_title() {
        return job_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.job_title
     *
     * @param job_title the value for cloud_user.job_title
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setJob_title(String job_title) {
        this.job_title = job_title == null ? null : job_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.student_number
     *
     * @return the value of cloud_user.student_number
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Integer getStudent_number() {
        return student_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.student_number
     *
     * @param student_number the value for cloud_user.student_number
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setStudent_number(Integer student_number) {
        this.student_number = student_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.role_id
     *
     * @return the value of cloud_user.role_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public Long getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.role_id
     *
     * @param role_id the value for cloud_user.role_id
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setRole_id(Long role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_user.salt
     *
     * @return the value of cloud_user.salt
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_user.salt
     *
     * @param salt the value for cloud_user.salt
     *
     * @mbg.generated Fri Jan 19 18:21:39 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}